# Network settings.
[Network]

# Address of the gRPC server.
# Example: ":8888"
GRPC = ":8888"

# Address of the REST server. If empty, no REST server is started.
# Example: ":6071"
FastHTTP = ""

# Mechanism for balancing within servers.
[Balancer]
On = true

# Balancing only mode.
BalancingOnly = false

# Mechanism for transaction logging.
[TransactionLogger]
On = true

# Directory where transaction logs are stored.
# Example: "transaction-logger"
BackupDirectory = "transaction-logger"

# Buffer size.
BufferSize = "1s"

# Параметры шифрования.
[Encryption]
# Key used for data encryption.
# Must be an AES key, 16, 24, or 32 bytes long to select AES-128, AES-192, or AES-256.
# Example: "PLEASE CHANGE ME" = 16 bytes -> AES-128.
# DO NOT CHANGE THE NUMBER OF BYTES AFTER THE FIRST PRODUCTION RUN.
Key = "PLEASE CHANGE ME"

# Web application settings.
[WebApp]
On = true

# Host of the web application.
# Example: "127.0.0.1:8080"
Host = ":8074"

# Allows you to enable or disable logs for a web application.
Logs = false

# Security settings.
[Security]
On = true

# Mandatory authorization.
# If false, authentication is not required for keys and objects that has Default level.
MandatoryAuthorization = true

[Logging]
Level = "debug"