[Storage]

# Storage will save transactions to disk in case of a failure.
TransactionLoggerDir = true

# Balancer IP:PORT
Balancer = "127.0.0.1:8888"

[Balancer]

# Balancer IP:PORT
Address = ":8888"

# Balancer RPS Limit
MaxRPS = 35000
